- name: Create dest directory if not exists
  become: yes
  file:
    path: "/usr/local/golang-{{ version }}"
    state: directory

- name: get specified version archive
  become: yes
  get_url:
    url: "{{ golang.src }}"
    dest: /tmp
- name: unarchive specified version package  
  become: yes
  unarchive:
    src: /tmp/go{{ version }}.{{ arch }}.tar.gz
    dest: /usr/local/go/

- name: add golang path
  become: yes
  template:
    src: golang.sh
    dest: /etc/profile.d/golang.sh
