- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: "roles/langs.rust/tasks/main: Install Rust"
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: cargo_exists is failed

- name: "roles/langs.rust/tasks/main: Add PATH for Rust"
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Rust"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/.cargo/bin:$PATH
  when: cargo_exists is failed

- name: "roles/langs.rust/tasks/main: Update to 1.62.0"
  command: /home/isucon/.cargo/bin/rustup update 1.62.0
  when: cargo_exists is failed
