- name: uninstall mariadb-server
  become: True
  apt:
    name: mariadb*
    state: absent
    purge: true

- name: apt autoremove
  become: True
  apt:
    purge: true
    autoremove: true

- name: install mysql-server
  become: true
  apt:
    name: mysql-server
  notify: restart_mysql

- name: put mysql conf
  become: true
  copy:
    src: zz-isucon.cnf
    dest: /etc/mysql/mysql.conf.d/zz-isucon.cnf
  notify: restart_mysql

- name: change systemd service unit for mysql
  become: true
  ini_file:
    path: /lib/systemd/system/mysql.service
    section: Service
    option: LimitNOFILE
    value: 65535
  notify: restart_mysql
