- name: install nginx
  apt:
    name: nginx

- name: check nginx conf
  stat:
    path: /etc/nginx/nginx.conf.orig
  register: conf

- name: backup nginx conf file
  copy:
    remote_src: yes
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf.orig
  when: not conf.stat.exists

- name: put nginx conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart_nginx

- name: create cache directory
  file:
    path: /var/cache/nginx/cache
    state: directory
    mode: 0777
  notify: restart_nginx

- name: change systemd service unit for nginx
  ini_file:
    path: /lib/systemd/system/nginx.service
    section: Service
    option: LimitNOFILE
    value: 65535
  notify: restart_nginx
