mysql_user: isucon
mysql_password: isucon
mysql_database: isucondition
discord_webhooks_url: https://discord.com/api/webhooks/995999400910409778/ZBLleRPMVog9E6f6pAjtBrDIeqeyVr6AUHPGn-qE7U2Mo7hOXZaA-k-ZsCY2EiFbGBX0
