- name: "check '/usr/local/bin/discordcat' if exist"
  stat:
    path: /usr/local/bin/discordcat
  register: discordcat_result

- name: debug
  debug:
    var: discordcat_result
  when: ansible_check_mode

- name: download discordcat
  get_url:
    url: https://github.com/k-nasa/discordcat/releases/download/0.1.0/discordcat_x86_64-unknown-linux-gnu.tar.gz
    checksum: sha1:8D69F394A66CF314BD580B7D9271A9FCCB9DCBD8
    dest: /tmp/discordcat_x86_64-unknown-linux-gnu.tar.gz
  when: not(discordcat_result.stat.exists)
  register: discordcat_get_url_result

- name: debug
  debug:
    var: discordcat_get_url_result
  when: ansible_check_mode

- name: unarchive discordcat
  unarchive:
    remote_src: yes
    src: /tmp/discordcat_x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp/
  when: not(discordcat_result.stat.exists) and not(ansible_check_mode)

- name: move , 0755
  copy:
    remote_src: yes
    src: /tmp/discordcat_x86_64-unknown-linux-gnu/discordcat
    dest: /usr/local/bin/
    mode: 0755
  when: not(discordcat_result.stat.exists) and not(ansible_check_mode)
