---
- hosts: all
  roles:
    - common.common
    - post.discordcat
    - util.netdata
    - lb.nginx
    - lb.alp
    - lb.restart
    - db.mysql
    - db.restart
    - db.pt_query_digest
    - lang.rust
