- name: install dstat (alternative of netdata!)
  apt:
    name: dstat

- name: check if /lib/systemd/system/netdata.service exists
  stat:
    path: /lib/systemd/system/netdata.service
  register: netdata_result

- name: download install script for netdata
  get_url:
    url: https://my-netdata.io/kickstart-static64.sh
    dest: /tmp/netdata.sh
    mode: 0755
  register: netdata
  when: not(netdata_result.stat.exists) and not(ansible_check_mode)

- name: install netdata
  shell: yes | /tmp/netdata.sh
  when: netdata.changed and not(ansible_check_mode)

- name: put netdata mysql conf
  become: true
  copy:
    src: mysql.conf
    dest: /etc/netdata/go.d/mysql.conf
    mode: 0644
