name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible playbook
        run: |
          ansible-playbook playbooks/local.yml
