name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Run ansible playbook
      #   run: |
      #     ansible-playbook playbooks/local.yml
      # - name: Rerun ansible playbook
      #   run: |
      #     ansible-playbook playbooks/local.yml
      - name: Docker run ubuntu
        env:
          DOCKER_REGISTRY_URL: https://hub.docker.com/
        run: sudo docker run -d -t --name=mycontainer ubuntu:18.04

      # - name: Install Ansible galaxy roles
      #   run: ansible-galaxy install -r roles/requirements.yml

      - name: ansible
        run: ansible-playbook -i 'mycontainer,' -c docker -u root playbooks/ci.yml  -e 'ansible_python_interpreter=/usr/bin/python3'
